menu:
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}
- {name: 'Posts', url: '/posts'}

social:
- {icon: 'github', link: 'https://github.com/Jgbergen18'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jamiebergen/'}

contacts:
- {name: 'Jamie Bergen', phone: '2036448464', email: 'jgbergen18@gmail.com', linkedin: 'https://www.linkedin.com/in/jamiebergen/',  image: 'assets/img/contact.jpg'}

projects:
- {name: 'Parkinsons Disease Research: ', url: 'PD-research'}
- {name: 'Neuron Counting Neural Network', url: 'neuron-counting-neural-network'}

