menu:
- {name: 'publications', url: '/publications'}
- {name: 'projects', url: '/projects'}
- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/Jgbergen18'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jamiebergen/'}

contacts:
- {name: 'Jamie Bergen', phone: '2036448464', email: 'jgbergen18@gmail.com', linkedin: 'https://www.linkedin.com/in/jamiebergen/',  image: 'assets/img/contact.jpg'}

project:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}
