menu:
- {name: 'publications', url: '/publications'}

- {name: 'cv', url: '/cv'}
- {name: 'contact', url: '/contact'}

social:
- {icon: 'github', link: 'https://github.com/Jgbergen18'}
- {icon: 'linkedin', link: 'https://www.linkedin.com/in/jamiebergen/'}

contacts:
- {name: 'Jamie Bergen', phone: '2036448464', email: 'jgbergen18@gmail.com', image: 'assets/img/contact.jpg'}
